kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-repository-map
data:
  repositories.yaml: |
    {{- with .Values.github.repositories }}
    {{- toYaml . | nindent 4 }}
    {{ end }}