spec:
  rules:
    - host: <workflows_host_name>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-workflows-server
                port:
                  number: 80
          - path: /api/webhook
            pathType: Prefix
            backend:
              service:
                name:  argo-workflow-ci-github-eventsource-eventsource-svc
                port:
                  number: 12000